# Docker Compose file for Playfolio API development
# Reference: https://docs.docker.com/compose/compose-file/

services:
  playfolio-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3777:3777"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-appdb}
      NEXT_PUBLIC_DEVICE_NAME: DB_Server
      PLAYFOLIO_ADMIN_KEY: supersecretkey
    restart: unless-stopped 
    volumes:
      # Only mount source files that you actively edit
      - ./src:/app/src:ro
      - ./public:/app/public:ro  
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        npx drizzle-kit push --config=drizzle.config.ts &&
        echo 'Database schema updated, starting Next.js...' &&
        echo 'Starting Next.js on 0.0.0.0:3777...' &&
        npm run dev -- --hostname 0.0.0.0 --port 3777
      "

  playfolio-admin:
    build:
      context: https://github.com/mjlemay/playfolio-admin.git#main
      dockerfile: Dockerfile
    ports:
      - "4400:4400"  # Admin interface on different port
    environment:
      NODE_ENV: development
      PLAYFOLIO_API_URL: http://0.0.0.0:3777
      PLAYFOLIO_ADMIN_KEY: supersecretkey
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      playfolio-api:
        condition: service_started
    networks:
      - default

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:standalone 
    restart: unless-stopped   
    ports:
      - 8080:8080

volumes:
  db_data:
    driver: local
    name: playfolio_db_data